import type { ResolvedReport } from './document.ts';

/**
 * Document front matter.
 *
 * A cover page is the first thing a reviewer judges, and the difference between
 * "clean" and "professional" is mostly information architecture rather than
 * decoration: a document-type label, a clear title block, who it was prepared
 * for and by, and a document control table carrying version, status, date and
 * classification.
 *
 * This module decides *what* appears on the cover. Each renderer decides how to
 * draw it, so DOCX, PDF and HTML carry the same information in their own
 * idioms.
 */

export interface CoverField {
  label: string;
  value: string;
}

export interface CoverModel {
  /** e.g. "Technical Report", "Incident Postmortem". Sits above the title. */
  documentType: string;
  title: string;
  subtitle: string | null;
  /**
   * The project this documents, shown as context. Null when it is the same as
   * the title — a cover that prints the same words twice reads as a mistake.
   */
  project: string | null;
  /** Prepared-for / prepared-by block. Omitted entirely when empty. */
  preparedBy: string | null;
  preparedFor: string | null;
  /** Document control rows: version, status, date, classification. */
  control: CoverField[];
  /** Shown small at the foot of the cover. */
  classification: string;
  /** Sits under the control table on the cover page. */
  notice: string;
}

const TYPE_LABELS: Record<string, string> = {
  technical: 'Technical Report',
  'technical-lab': 'Laboratory Report',
  academic: 'Academic Report',
  'it-implementation': 'Implementation Report',
  'cloud-deployment': 'Cloud Deployment Report',
  'security-assessment': 'Security Assessment',
  incident: 'Incident Postmortem',
  'software-project': 'Software Project Report',
  executive: 'Executive Summary',
};

/** Audiences that imply the document leaves the author's own organisation. */
const EXTERNAL_AUDIENCES = new Set(['client', 'professor', 'interviewer']);

export function buildCover(report: ResolvedReport): CoverModel {
  const documentType = TYPE_LABELS[report.templateKey] ?? 'Report';
  const generated = new Date(report.generatedAt);

  const classification = EXTERNAL_AUDIENCES.has(report.meta.audience)
    ? 'For the named recipient'
    : 'Internal';

  return {
    documentType,
    title: report.title,
    subtitle: report.subtitle,
    project: report.projectTitle.trim() === report.title.trim() ? null : report.projectTitle,
    preparedBy: report.author,
    preparedFor: audienceLabel(report.meta.audience),
    control: [
      { label: 'Version', value: `${report.meta.version}.0` },
      { label: 'Date', value: formatDate(generated) },
      { label: 'Status', value: 'Issued' },
      { label: 'Classification', value: classification },
    ],
    classification,
    // The document belongs to the person who did the work; the tool drafted it
    // from their record. Saying it the other way round ("generated by
    // Fieldnote") reads as though nobody stood behind the findings, which is
    // both wrong and the opposite of what a report is for. The provenance
    // disclosure stays — it is the honest part, and it is what lets a reader
    // trust the rest.
    notice: report.author
      ? `Prepared by ${report.author} from their record of this work, drafted with AI assistance. ` +
        'Passages labelled Inferred or Recommendation are interpretation, not statements of what occurred.'
      : 'Prepared from the project record, drafted with AI assistance. Passages labelled ' +
        'Inferred or Recommendation are interpretation, not statements of what occurred.',
  };
}

/**
 * Who the document is addressed to. Returns null for internal-team audiences,
 * where a "Prepared for" line would be noise rather than information.
 */
function audienceLabel(audience: string): string | null {
  switch (audience) {
    case 'professor':
      return 'Course assessment';
    case 'client':
      return 'Client';
    case 'management':
      return 'Management';
    case 'security-team':
      return 'Security team';
    case 'interviewer':
      return 'Technical review';
    default:
      return null;
  }
}

export function formatDate(date: Date): string {
  // Long form on a cover page: "14 March 2026" reads better than an ISO stamp
  // and is unambiguous across regions, unlike 03/14.
  return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}
