import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  HeadingLevel,
  ImageRun,
  Packer,
  PageBreak,
  PageNumber,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableOfContents,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import type { ResolvedReport } from './document.ts';
import type { ReportBlock } from '../domain/types.ts';
import { calloutStyles, getTheme, type Theme } from './themes.ts';
import { buildCover } from './cover.ts';

/**
 * DOCX renderer.
 *
 * Produces a document with a real title page, a field-driven table of contents
 * (Word populates it on open), running headers, page numbers, numbered figure
 * captions and styled callouts — the things that make a Word file read as a
 * report rather than as pasted text.
 */

export async function renderReportDocx(report: ResolvedReport): Promise<Buffer> {
  const theme = getTheme(report.theme);
  const { palette, fonts } = theme;
  const MUTED = palette.muted;
  // Word measures type in half-points.
  const bodyHalfPt = Math.round(theme.bodyPt * 2);

  const body: (Paragraph | Table)[] = [];

  for (const section of report.sections) {
    body.push(
      new Paragraph({
        text: section.heading,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 360, after: 160 },
        ...(theme.sectionRule
          ? { border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: palette.line, space: 4 } } }
          : {}),
      }),
    );
    for (const block of section.blocks) body.push(...docxBlock(block, report, theme));
  }

  const doc = new Document({
    creator: report.author ?? 'Fieldnote',
    title: report.title,
    description: `Generated from the Fieldnote project "${report.projectTitle}"`,
    styles: {
      default: {
        document: {
          run: { font: fonts.body, size: bodyHalfPt, color: palette.ink },
          paragraph: { spacing: { line: 276, after: 120 } },
        },
        heading1: {
          run: { font: fonts.heading, size: bodyHalfPt + 10, bold: true, color: palette.heading },
          paragraph: { spacing: { before: 320, after: 140 } },
        },
        heading2: { run: { font: fonts.heading, size: bodyHalfPt + 4, bold: true, color: palette.heading } },
        heading3: { run: { font: fonts.heading, size: bodyHalfPt + 2, bold: true, color: palette.muted } },
      },
      paragraphStyles: [
        { id: 'Caption', name: 'Caption', basedOn: 'Normal', run: { size: 18, italics: true, color: MUTED }, paragraph: { spacing: { after: 240 } } },
        { id: 'CodeBlock', name: 'Code Block', basedOn: 'Normal', run: { font: fonts.mono, size: 18 }, paragraph: { spacing: { line: 240, after: 60 } } },
      ],
    },
    sections: [
      // Cover page and contents — no header/footer.
      {
        properties: { page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
        children: [
          ...coverPage(report, theme),
          new Paragraph({ children: [new PageBreak()] }),
          new Paragraph({ text: 'Contents', heading: HeadingLevel.HEADING_1 }),
          new TableOfContents('Contents', { hyperlink: true, headingStyleRange: '1-3' }),
          new Paragraph({ children: [new PageBreak()] }),
        ],
      },
      // Body — headers, footers and page numbers.
      {
        properties: { page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [new TextRun({ text: report.title, size: 18, color: MUTED })],
                border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: palette.line, space: 4 } },
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: 'Page ', size: 18, color: MUTED }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 18, color: MUTED }),
                  new TextRun({ text: ' of ', size: 18, color: MUTED }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 18, color: MUTED }),
                ],
              }),
            ],
          }),
        },
        children: [
          ...body,
          new Paragraph({ text: '', spacing: { before: 480 } }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by Fieldnote from the project record. Passages labelled Inferred or Recommendation are AI-generated interpretation, not statements of what occurred.',
                size: 16,
                color: MUTED,
                italics: true,
              }),
            ],
          }),
        ],
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

/**
 * The cover page.
 *
 * Left-aligned and sharing the body text column, with a document-type label
 * above the title and a document-control table at the foot. Word has no page
 * background, so a "filled" theme is expressed as a heavy accent band rather
 * than a colour wash — a shaded full page prints badly and looks wrong when
 * the reader edits the file.
 */
function coverPage(report: ResolvedReport, theme: Theme): Paragraph[] {
  const cover = buildCover(report);
  const { palette, fonts } = theme;
  const bandSize = theme.cover === 'filled' ? 36 : theme.cover === 'banded' ? 18 : 0;

  const parties: Paragraph[] = [];
  if (cover.preparedBy) parties.push(labelledLine('Prepared by', cover.preparedBy, theme));
  if (cover.preparedFor) parties.push(labelledLine('Prepared for', cover.preparedFor, theme));

  return [
    ...(bandSize > 0
      ? [
          new Paragraph({
            spacing: { after: 1400 },
            border: { bottom: { style: BorderStyle.SINGLE, size: bandSize, color: palette.accent, space: 1 } },
            children: [new TextRun({ text: '', size: 2 })],
          }),
        ]
      : [new Paragraph({ text: '', spacing: { before: 1600 } })]),

    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: cover.documentType.toUpperCase(),
          bold: true,
          size: 19,
          color: palette.accent,
          characterSpacing: 40,
          font: fonts.body,
        }),
      ],
    }),

    new Paragraph({
      spacing: { after: cover.subtitle ? 120 : 240 },
      children: [
        new TextRun({ text: cover.title, bold: true, size: 60, color: palette.heading, font: fonts.heading }),
      ],
    }),

    ...(cover.subtitle
      ? [
          new Paragraph({
            spacing: { after: 240 },
            children: [new TextRun({ text: cover.subtitle, size: 28, color: palette.muted, font: fonts.body })],
          }),
        ]
      : []),

    // A short accent rule under the title block.
    new Paragraph({
      spacing: { after: 320 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 18, color: palette.accent, space: 1 } },
      indent: { right: 8600 },
      children: [new TextRun({ text: '', size: 2 })],
    }),

    ...(cover.project ? [labelledLine('Project', cover.project, theme)] : []),
    new Paragraph({ text: '', spacing: { before: 900 } }),
    ...parties,
    new Paragraph({ text: '', spacing: { before: 600 } }),

    // Document control, as a rule-separated row of label/value pairs.
    new Paragraph({
      spacing: { before: 120, after: 120 },
      border: { top: { style: BorderStyle.SINGLE, size: 6, color: palette.line, space: 6 } },
      children: cover.control.flatMap((field, index) => [
        ...(index > 0 ? [new TextRun({ text: '     ', size: 18 })] : []),
        new TextRun({ text: `${field.label.toUpperCase()}  `, size: 15, color: palette.muted, font: fonts.body }),
        new TextRun({ text: field.value, bold: true, size: 19, color: palette.ink, font: fonts.body }),
      ]),
    }),

    new Paragraph({
      spacing: { before: 400 },
      children: [new TextRun({ text: cover.notice, size: 15, italics: true, color: palette.muted })],
    }),
  ];
}

function labelledLine(label: string, value: string, theme: Theme): Paragraph {
  return new Paragraph({
    spacing: { after: 60 },
    children: [
      new TextRun({ text: `${label}  `, size: 20, color: theme.palette.muted, font: theme.fonts.body }),
      new TextRun({ text: value, size: 21, color: theme.palette.ink, font: theme.fonts.body }),
    ],
  });
}

function docxBlock(block: ReportBlock, report: ResolvedReport, theme: Theme): (Paragraph | Table)[] {
  const { palette, fonts } = theme;
  const MUTED = palette.muted;
  switch (block.type) {
    case 'paragraph':
      return [new Paragraph({ children: [new TextRun(block.text)] })];

    case 'heading':
      return [
        new Paragraph({
          text: block.text,
          heading: block.level === 2 ? HeadingLevel.HEADING_2 : block.level === 3 ? HeadingLevel.HEADING_3 : HeadingLevel.HEADING_4,
          spacing: { before: 240, after: 120 },
        }),
      ];

    case 'bullets':
      return block.items.map(
        (item) =>
          new Paragraph({
            text: item,
            ...(block.ordered ? { numbering: { reference: 'default-numbering', level: 0 } } : { bullet: { level: 0 } }),
          }),
      );

    case 'procedure':
      return block.items.flatMap((item, index) => [
        new Paragraph({ children: [new TextRun({ text: `${index + 1}. `, bold: true }), new TextRun({ text: item.text, bold: true })] }),
        ...(item.detail
          ? [new Paragraph({ indent: { left: 360 }, children: [new TextRun({ text: item.detail, color: MUTED })] })]
          : []),
      ]);

    case 'code': {
      const lines = block.content.split('\n');
      return [
        ...lines.map(
          (line, index) =>
            new Paragraph({
              style: 'CodeBlock',
              shading: { type: ShadingType.SOLID, color: palette.surface, fill: palette.surface },
              border: {
                left: { style: BorderStyle.SINGLE, size: 12, color: palette.line, space: 6 },
                ...(index === 0 ? { top: { style: BorderStyle.SINGLE, size: 4, color: palette.line, space: 4 } } : {}),
                ...(index === lines.length - 1 ? { bottom: { style: BorderStyle.SINGLE, size: 4, color: palette.line, space: 4 } } : {}),
              },
              children: [new TextRun({ text: line || ' ', font: fonts.mono, size: 18 })],
            }),
        ),
        ...(block.caption ? [new Paragraph({ style: 'Caption', text: block.caption })] : []),
      ];
    }

    case 'table': {
      const table = new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            tableHeader: true,
            children: block.headers.map(
              (header) =>
                new TableCell({
                  shading: { type: ShadingType.SOLID, color: palette.surface, fill: palette.surface },
                  children: [new Paragraph({ children: [new TextRun({ text: header, bold: true, size: 20 })] })],
                }),
            ),
          }),
          ...block.rows.map(
            (row) =>
              new TableRow({
                children: row.map(
                  (cell) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(cell), size: 20 })] })] }),
                ),
              }),
          ),
        ],
      });
      return block.caption ? [table, new Paragraph({ style: 'Caption', text: block.caption })] : [table];
    }

    case 'figure': {
      const figure = report.figures.get(block.evidenceId);
      if (!figure?.bytes) {
        return [
          new Paragraph({
            children: [new TextRun({ text: `[Figure ${block.number ?? '?'} unavailable: ${figure?.missingReason ?? 'not found'}]`, italics: true, color: MUTED })],
          }),
        ];
      }
      const { width, height } = fitImage(figure.width, figure.height, 520, 380);
      return [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new ImageRun({
              data: figure.bytes,
              transformation: { width, height },
              type: imageTypeFor(figure.mimeType),
            }),
          ],
        }),
        new Paragraph({
          style: 'Caption',
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: `Figure ${block.number ?? '?'} — ${block.caption}`, italics: true, size: 18, color: MUTED })],
        }),
      ];
    }

    case 'callout': {
      const styles = calloutStyles(theme);
      const style = styles[block.variant] ?? styles.note!;
      return [
        new Paragraph({
          shading: { type: ShadingType.SOLID, color: style.fill, fill: style.fill },
          border: { left: { style: BorderStyle.SINGLE, size: 18, color: style.bar, space: 8 } },
          spacing: { before: 120, after: 120 },
          children: [
            new TextRun({ text: `${style.label}: `, bold: true, size: 20, color: style.ink }),
            new TextRun({ text: block.text, size: 20, color: style.ink }),
          ],
        }),
      ];
    }

    case 'diagram':
      return [
        ...(block.title ? [new Paragraph({ children: [new TextRun({ text: block.title, bold: true })] })] : []),
        ...block.ascii.split('\n').map(
          (line) => new Paragraph({ style: 'CodeBlock', children: [new TextRun({ text: line || ' ', font: fonts.mono, size: 18 })] }),
        ),
        ...(block.caption ? [new Paragraph({ style: 'Caption', text: block.caption })] : []),
      ];

    case 'reference-list':
      return block.items.map(
        (item, index) =>
          new Paragraph({
            children: [
              new TextRun({ text: `[${index + 1}] `, bold: true }),
              new TextRun({ text: item.label }),
              ...(item.url ? [new TextRun({ text: ` — ${item.url}`, color: palette.accent })] : []),
              ...(item.detail ? [new TextRun({ text: ` — ${item.detail}`, color: MUTED })] : []),
            ],
          }),
      );

    default:
      return [];
  }
}

function imageTypeFor(mimeType: string | null): 'png' | 'jpg' | 'gif' | 'bmp' {
  switch (mimeType) {
    case 'image/jpeg':
      return 'jpg';
    case 'image/gif':
      return 'gif';
    case 'image/bmp':
      return 'bmp';
    default:
      return 'png';
  }
}

export function fitImage(
  width: number | null,
  height: number | null,
  maxWidth: number,
  maxHeight: number,
): { width: number; height: number } {
  if (!width || !height) return { width: maxWidth, height: Math.round(maxWidth * 0.62) };
  const scale = Math.min(maxWidth / width, maxHeight / height, 1);
  return { width: Math.round(width * scale), height: Math.round(height * scale) };
}
