import type { ResolvedPresentation, ResolvedReport } from './document.ts';
import type { ReportBlock } from '../domain/types.ts';
import { calloutStyles, getTheme, hex } from './themes.ts';
import { buildCover } from './cover.ts';

/** Markdown and self-contained HTML renderers. */

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// --- Markdown -------------------------------------------------------------

export function renderReportMarkdown(report: ResolvedReport): string {
  const out: string[] = [
    `# ${report.title}`,
    '',
    report.subtitle ? `*${report.subtitle}*` : '',
    '',
    `**Project:** ${report.projectTitle}  `,
    report.author ? `**Author:** ${report.author}  ` : '',
    `**Generated:** ${new Date(report.generatedAt).toISOString().slice(0, 10)}`,
    '',
    '## Contents',
    '',
    ...report.sections.map((s, i) => `${i + 1}. [${s.heading}](#${slugAnchor(s.heading)})`),
    '',
    '---',
    '',
  ];

  for (const section of report.sections) {
    out.push(`## ${section.heading}`, '');
    for (const block of section.blocks) out.push(...markdownBlock(block), '');
  }

  out.push('---', '', `<sub>Generated by Fieldnote. Statements marked as inference or recommendation are AI-generated and not statements of fact.</sub>`);
  return out.filter((line) => line !== undefined).join('\n').replace(/\n{3,}/g, '\n\n');
}

function markdownBlock(block: ReportBlock): string[] {
  switch (block.type) {
    case 'paragraph':
      return [block.text];
    case 'heading':
      return [`${'#'.repeat(block.level)} ${block.text}`];
    case 'bullets':
      return block.items.map((item, i) => (block.ordered ? `${i + 1}. ${item}` : `- ${item}`));
    case 'procedure':
      return block.items.map((item, i) => `${i + 1}. **${item.text}**${item.detail ? `  \n   ${item.detail}` : ''}`);
    case 'code':
      return [`\`\`\`${block.language}`, block.content, '```', block.caption ? `*${block.caption}*` : ''];
    case 'table':
      return [
        block.caption ? `**${block.caption}**` : '',
        `| ${block.headers.join(' | ')} |`,
        `| ${block.headers.map(() => '---').join(' | ')} |`,
        ...block.rows.map((row) => `| ${row.map((cell) => String(cell).replace(/\|/g, '\\|')).join(' | ')} |`),
      ];
    case 'figure':
      return [`**Figure ${block.number ?? '?'}** — ${block.caption}`, '', `> _Image: evidence \`${block.evidenceId}\`_`];
    case 'callout': {
      const prefix = { note: 'Note', warning: 'Caution', inference: 'Inferred', recommendation: 'Recommendation' }[block.variant];
      return [`> **${prefix}:** ${block.text}`];
    }
    case 'diagram':
      return [block.title ? `**${block.title}**` : '', '```text', block.ascii, '```', block.caption ? `*${block.caption}*` : ''];
    case 'reference-list':
      return block.items.map((item, i) => `${i + 1}. ${item.label}${item.url ? ` — <${item.url}>` : ''}${item.detail ? ` — ${item.detail}` : ''}`);
    default:
      return [];
  }
}

export function renderPresentationMarkdown(presentation: ResolvedPresentation): string {
  const out: string[] = [`# ${presentation.title}`, ''];
  if (presentation.subtitle) out.push(`*${presentation.subtitle}*`, '');
  if (presentation.presenter) out.push(`**Presenter:** ${presentation.presenter}`, '');

  for (const slide of presentation.slides) {
    out.push('---', '', `## Slide ${slide.position + 1}: ${slide.title}`, '');
    if (slide.subtitle) out.push(`*${slide.subtitle}*`, '');
    for (const bullet of slide.bullets) out.push(`- ${bullet}`);
    if (slide.body.table) {
      out.push(
        '',
        `| ${slide.body.table.headers.join(' | ')} |`,
        `| ${slide.body.table.headers.map(() => '---').join(' | ')} |`,
        ...slide.body.table.rows.map((r) => `| ${r.join(' | ')} |`),
      );
    }
    if (slide.body.code) out.push('', `\`\`\`${slide.body.code.language}`, slide.body.code.content, '```');
    if (slide.body.diagram) out.push('', '```text', slide.body.diagram.ascii, '```');
    if (slide.body.before || slide.body.after) {
      out.push('');
      if (slide.body.before) out.push(`**${slide.body.before.heading}**`, ...slide.body.before.bullets.map((b) => `- ${b}`));
      if (slide.body.after) out.push(`**${slide.body.after.heading}**`, ...slide.body.after.bullets.map((b) => `- ${b}`));
    }
    for (const figure of slide.figures) out.push('', `_Figure: ${figure.caption}_`);
    if (slide.speakerNotes) out.push('', '**Speaker notes**', '', slide.speakerNotes);
    out.push('');
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

// --- HTML -----------------------------------------------------------------

function reportCss(themeKey: string): string {
  const theme = getTheme(themeKey);
  const p = theme.palette;
  const callouts = calloutStyles(theme);
  const serif = theme.fonts.body === 'Cambria';
  const stack = serif
    ? 'Cambria, Georgia, "Times New Roman", serif'
    : '"Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif';

  return `
:root { color-scheme: light dark;
  --ink:${hex(p.ink)}; --muted:${hex(p.muted)}; --heading:${hex(p.heading)};
  --line:${hex(p.line)}; --bg:${hex(p.page)}; --accent:${hex(p.accent)}; --note:${hex(p.surface)};
  --cover:${hex(p.cover)}; --cover-ink:${hex(p.coverInk)}; --cover-muted:${hex(p.coverMuted)};
  --warn:${hex(callouts.warning!.fill)}; --warn-ink:${hex(callouts.warning!.ink)};
  --infer:${hex(callouts.inference!.fill)}; --infer-ink:${hex(callouts.inference!.ink)};
  --rec:${hex(callouts.recommendation!.fill)}; --rec-ink:${hex(callouts.recommendation!.ink)};
  --body-size:${theme.bodyPt + 4}px; }
/* Dark mode inverts the reading surface but keeps the theme's accent, so a
   Forest report stays green rather than reverting to a generic blue. */
@media (prefers-color-scheme: dark) { :root { --ink:#e5e7eb; --muted:#9ca3af; --heading:#f3f4f6;
  --line:#374151; --bg:#0b0f17; --note:#1f2937;
  --warn:#3f2d0e; --warn-ink:#fbbf24; --infer:#1e1b4b; --infer-ink:#c7d2fe;
  --rec:#052e21; --rec-ink:#6ee7b7; } }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font: var(--body-size)/1.65 ${stack}; }
.page { max-width: 46rem; margin: 0 auto; padding: 3rem 1.5rem 6rem; }
h1 { font-size: 2.1rem; line-height:1.2; margin:0 0 .5rem; letter-spacing:-.02em; color:var(--heading); }
h2 { font-size:1.4rem; margin:2.75rem 0 .75rem; padding-bottom:.35rem; color:var(--heading);
     border-bottom:${theme.sectionRule ? '1px solid var(--line)' : '0'}; }
h3 { font-size:1.1rem; margin:1.75rem 0 .5rem; color:var(--heading); }
h4 { font-size:1rem; margin:1.25rem 0 .35rem; color:var(--muted); }
p { margin:0 0 .9rem; }
.meta { color:var(--muted); font-size:.9rem; margin-bottom:2rem; }
.toc { background:var(--note); border-radius:10px; padding:1rem 1.25rem; margin:2rem 0; }
.toc ol { margin:.25rem 0 0; padding-left:1.25rem; }
.toc a { color:inherit; }
pre { background:var(--note); border:1px solid var(--line); border-radius:8px; padding:.85rem 1rem;
  overflow-x:auto; font-size:.85rem; line-height:1.5; }
code { font-family: "Cascadia Code", Consolas, "SF Mono", Menlo, monospace; }
table { width:100%; border-collapse:collapse; margin:1rem 0; font-size:.92rem; display:block; overflow-x:auto; }
th, td { border:1px solid var(--line); padding:.5rem .65rem; text-align:left; vertical-align:top; }
th { background:var(--note); font-weight:600; }
figure { margin:1.5rem 0; }
figure img { max-width:100%; height:auto; border:1px solid var(--line); border-radius:8px; display:block; }
figcaption { color:var(--muted); font-size:.85rem; margin-top:.5rem; }
.callout { border-left:3px solid var(--accent); border-radius:0 8px 8px 0; padding:.75rem 1rem; margin:1rem 0; }
.callout.note { background:var(--note); }
.callout.warning { background:var(--warn); border-left-color:${hex(callouts.warning!.bar)}; color:var(--warn-ink); }
.callout.inference { background:var(--infer); border-left-color:${hex(callouts.inference!.bar)}; color:var(--infer-ink); }
.callout.recommendation { background:var(--rec); border-left-color:${hex(callouts.recommendation!.bar)}; color:var(--rec-ink); }
.callout .label { display:block; font-size:.72rem; letter-spacing:.08em; text-transform:uppercase;
  font-weight:700; opacity:.75; margin-bottom:.2rem; }
.footer { margin-top:4rem; padding-top:1rem; border-top:1px solid var(--line); color:var(--muted); font-size:.82rem; }
/* The cover mirrors the DOCX and PDF title pages: type label, title block,
   accent rule, parties, and a document-control row. */
.cover { margin:-3rem -1.5rem 3rem; padding:5rem 1.5rem 2.5rem; }
.cover.filled { background:var(--cover); color:var(--cover-ink); }
.cover.filled h1, .cover.filled .doc-type { color:var(--cover-ink); }
.cover.filled .cover-sub, .cover.filled .cover-line, .cover.filled .ctrl-label,
.cover.filled .cover-notice { color:var(--cover-muted); }
.cover.filled .ctrl-value { color:var(--cover-ink); }
.cover.filled .control { border-top-color:var(--cover-muted); }
.cover.banded { border-top:10px solid var(--accent); padding-top:4.5rem; }
.cover .doc-type { font-size:.72rem; font-weight:700; letter-spacing:.16em;
  text-transform:uppercase; color:var(--accent); margin-bottom:.9rem; }
.cover h1 { font-size:2.6rem; line-height:1.12; margin:0 0 .5rem; }
.cover .cover-sub { font-size:1.1rem; color:var(--muted); margin:0 0 1rem; }
.cover .cover-rule { width:96px; height:3px; background:var(--accent); margin:1.25rem 0 1.5rem; }
.cover .cover-line { font-size:.92rem; color:var(--muted); margin:0 0 .3rem; }
.cover .cover-line strong { color:var(--ink); font-weight:600; }
.cover .parties { margin-top:2.5rem; }
.cover .control { display:flex; flex-wrap:wrap; gap:2.5rem; margin-top:3rem;
  padding-top:1rem; border-top:1px solid var(--line); }
.cover .ctrl-label { font-size:.66rem; font-weight:700; letter-spacing:.1em;
  text-transform:uppercase; color:var(--muted); margin-bottom:.15rem; }
.cover .ctrl-value { font-size:.95rem; font-weight:600; }
.cover .cover-notice { margin-top:2rem; font-size:.75rem; font-style:italic; color:var(--muted); }
@media print { body { background:#fff; color:#000; } .page { max-width:none; padding:0; } h2 { page-break-after:avoid; }
  figure, pre, table { page-break-inside:avoid; } }
`;
}

export function renderReportHtml(report: ResolvedReport): string {
  const body: string[] = [];
  for (const section of report.sections) {
    body.push(`<h2 id="${slugAnchor(section.heading)}">${escapeHtml(section.heading)}</h2>`);
    for (const block of section.blocks) body.push(htmlBlock(block, report));
  }

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(report.title)}</title>
<style>${reportCss(report.theme)}</style></head>
<body><main class="page">
${renderCover(report)}
<nav class="toc"><strong>Contents</strong><ol>
${report.sections.map((s) => `<li><a href="#${slugAnchor(s.heading)}">${escapeHtml(s.heading)}</a></li>`).join('\n')}
</ol></nav>
${body.join('\n')}
<p class="footer">Passages marked <em>Inferred</em> or <em>Recommendation</em> are AI-generated
interpretation, not statements of what occurred.</p>
</main></body></html>`;
}

function htmlBlock(block: ReportBlock, report: ResolvedReport): string {
  switch (block.type) {
    case 'paragraph':
      return `<p>${escapeHtml(block.text)}</p>`;
    case 'heading':
      return `<h${block.level}>${escapeHtml(block.text)}</h${block.level}>`;
    case 'bullets': {
      const tag = block.ordered ? 'ol' : 'ul';
      return `<${tag}>${block.items.map((i) => `<li>${escapeHtml(i)}</li>`).join('')}</${tag}>`;
    }
    case 'procedure':
      return `<ol>${block.items
        .map((i) => `<li><strong>${escapeHtml(i.text)}</strong>${i.detail ? `<br><span class="meta">${escapeHtml(i.detail)}</span>` : ''}</li>`)
        .join('')}</ol>`;
    case 'code':
      return `<pre><code>${escapeHtml(block.content)}</code></pre>${block.caption ? `<p class="meta">${escapeHtml(block.caption)}</p>` : ''}`;
    case 'table':
      return `<table>${block.caption ? `<caption>${escapeHtml(block.caption)}</caption>` : ''}
        <thead><tr>${block.headers.map((h) => `<th>${escapeHtml(h)}</th>`).join('')}</tr></thead>
        <tbody>${block.rows.map((r) => `<tr>${r.map((c) => `<td>${escapeHtml(String(c))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
    case 'figure': {
      const figure = report.figures.get(block.evidenceId);
      const img = figure?.bytes
        ? `<img src="data:${figure.mimeType};base64,${figure.bytes.toString('base64')}" alt="${escapeHtml(block.caption)}">`
        : `<p class="meta">[Image unavailable: ${escapeHtml(figure?.missingReason ?? 'not found')}]</p>`;
      return `<figure>${img}<figcaption>Figure ${block.number ?? '?'} — ${escapeHtml(block.caption)}</figcaption></figure>`;
    }
    case 'callout': {
      const label = { note: 'Note', warning: 'Caution', inference: 'Inferred', recommendation: 'Recommendation' }[block.variant];
      return `<div class="callout ${block.variant}"><span class="label">${label}</span>${escapeHtml(block.text)}</div>`;
    }
    case 'diagram':
      return `<figure><pre><code>${escapeHtml(block.ascii)}</code></pre>${block.caption ? `<figcaption>${escapeHtml(block.caption)}</figcaption>` : ''}</figure>`;
    case 'reference-list':
      return `<ol>${block.items
        .map((i) => `<li>${escapeHtml(i.label)}${i.url ? ` — <a href="${escapeHtml(i.url)}">${escapeHtml(i.url)}</a>` : ''}${i.detail ? ` — ${escapeHtml(i.detail)}` : ''}</li>`)
        .join('')}</ol>`;
    default:
      return '';
  }
}

export function renderPresentationHtml(presentation: ResolvedPresentation): string {
  const slides = presentation.slides
    .map((slide) => {
      const figures = slide.figures
        .filter((f) => f.bytes)
        .map((f) => `<img src="data:${f.mimeType};base64,${f.bytes!.toString('base64')}" alt="${escapeHtml(f.caption)}">`)
        .join('');
      return `<section class="slide">
        <h2>${escapeHtml(slide.title)}</h2>
        ${slide.subtitle ? `<p class="sub">${escapeHtml(slide.subtitle)}</p>` : ''}
        <ul>${slide.bullets.map((b) => `<li>${escapeHtml(b)}</li>`).join('')}</ul>
        ${slide.body.code ? `<pre><code>${escapeHtml(slide.body.code.content)}</code></pre>` : ''}
        ${slide.body.diagram ? `<pre><code>${escapeHtml(slide.body.diagram.ascii)}</code></pre>` : ''}
        ${figures ? `<div class="figures">${figures}</div>` : ''}
        ${slide.speakerNotes ? `<aside class="notes"><strong>Speaker notes</strong><p>${escapeHtml(slide.speakerNotes)}</p></aside>` : ''}
      </section>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(presentation.title)}</title>
<style>${reportCss(presentation.theme)}
.slide { border:1px solid var(--line); border-radius:12px; padding:1.5rem 1.75rem; margin:1.5rem 0; }
.slide h2 { border:0; margin-top:0; }
.slide .sub { color:var(--muted); margin-top:-.35rem; }
.slide ul { font-size:1.05rem; }
.figures { display:flex; gap:1rem; flex-wrap:wrap; }
.figures img { max-width:min(100%, 22rem); border:1px solid var(--line); border-radius:8px; }
.notes { background:var(--note); border-radius:8px; padding:.85rem 1rem; margin-top:1rem; font-size:.9rem; }
</style></head>
<body><main class="page">
<h1>${escapeHtml(presentation.title)}</h1>
${presentation.presenter ? `<p class="meta">${escapeHtml(presentation.presenter)}</p>` : ''}
${slides}
</main></body></html>`;
}

/** The HTML cover, carrying the same blocks as the DOCX and PDF title pages. */
function renderCover(report: ResolvedReport): string {
  const cover = buildCover(report);
  const theme = getTheme(report.theme);

  const parties = [
    cover.preparedBy ? { label: 'Prepared by', value: cover.preparedBy } : null,
    cover.preparedFor ? { label: 'Prepared for', value: cover.preparedFor } : null,
  ].filter((party): party is { label: string; value: string } => party !== null);

  return `<header class="cover ${theme.cover}">
  <div class="doc-type">${escapeHtml(cover.documentType)}</div>
  <h1>${escapeHtml(cover.title)}</h1>
  ${cover.subtitle ? `<p class="cover-sub">${escapeHtml(cover.subtitle)}</p>` : ''}
  <div class="cover-rule"></div>
  ${cover.project ? `<p class="cover-line">Project &nbsp;<strong>${escapeHtml(cover.project)}</strong></p>` : ''}
  ${
    parties.length > 0
      ? `<div class="parties">${parties
          .map((p) => `<p class="cover-line">${p.label} &nbsp;<strong>${escapeHtml(p.value)}</strong></p>`)
          .join('')}</div>`
      : ''
  }
  <div class="control">
    ${cover.control
      .map(
        (field) =>
          `<div><div class="ctrl-label">${escapeHtml(field.label)}</div>` +
          `<div class="ctrl-value">${escapeHtml(field.value)}</div></div>`,
      )
      .join('')}
  </div>
  <p class="cover-notice">${escapeHtml(cover.notice)}</p>
</header>`;
}

function slugAnchor(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}
